# Generated by Django 6.0.5 on 2026-06-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_historialbusqueda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialbusqueda',
            name='motivo',
        ),
    ]
