# Generated by Django 6.0.5 on 2026-06-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_remove_historialbusqueda_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arancel',
            name='notas_explicativas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Explicativas y Legales'),
        ),
    ]
