# Generated by Django 6.0.5 on 2026-06-20 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_arancel_notas_explicativas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Agregado el')),
                ('arancel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.arancel', verbose_name='Partida Arancelaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Partida Recurrente',
                'verbose_name_plural': 'Partidas Recurrentes',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'arancel')},
            },
        ),
    ]
