# Generated by Django 6.0.5 on 2026-06-20 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_partidarecurrente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Color (hex)')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Categoría de Partida Recurrente',
                'verbose_name_plural': 'Categorías de Partidas Recurrentes',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='partidarecurrente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.categoriarecurrente', verbose_name='Categoría'),
        ),
    ]
