<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-24 07:59
=======
# Generated by Django 6.0.5 on 2026-05-18 17:22
>>>>>>> 45c860e9f0c9e664c4e61c94ca0a1f6104af8670

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('partida_arancelaria', 'Error en Partida Arancelaria'), ('codigo_producto', 'Error en Código de Producto'), ('tarifa', 'Error en Tarifa/Arancel'), ('descripcion', 'Error en Descripción'), ('busqueda', 'Error en Búsqueda'), ('visualizacion', 'Error de Visualización'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('descripcion', models.TextField()),
                ('partida_arancelaria_afectada', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_producto_afectado', models.CharField(blank=True, max_length=50, null=True)),
                ('captura_pantalla', models.ImageField(blank=True, null=True, upload_to='reportes_errores/capturas/%Y/%m/')),
                ('nombre_reportante', models.CharField(max_length=100)),
                ('email_reportante', models.EmailField(max_length=254)),
                ('es_usuario_registrado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_admin', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
