# Generated by Django 6.0.5 on 2026-06-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0004_arancel_notas_explicativas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('resolucion', 'Resolución'), ('caso_estudio', 'Caso de Estudio'), ('circular', 'Circular'), ('normativa', 'Normativa'), ('dictamen', 'Dictamen Técnico'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Documento')),
                ('descripcion', models.TextField(verbose_name='Descripción / Contenido')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='referencias/archivos/%Y/%m/', verbose_name='Archivo (PDF)')),
                ('enlace', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace externo')),
                ('entidad_emisora', models.CharField(choices=[('aduana_nacional', 'Aduana Nacional'), ('ministerio', 'Ministerio'), ('senavexi', 'SENAVEXI'), ('ibce', 'IBCE'), ('otra', 'Otra')], max_length=50, verbose_name='Entidad Emisora')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('codigos_arancelarios', models.ManyToManyField(blank=True, to='cuentas.arancel', verbose_name='Códigos Arancelarios Relacionados')),
            ],
            options={
                'verbose_name': 'Referencia de Clasificación',
                'verbose_name_plural': 'Referencias de Clasificación',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
