# Generated by Django 6.0.5 on 2026-06-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteerror',
            name='captura_pantalla',
            field=models.ImageField(blank=True, null=True, upload_to='capturas/%Y/%m/'),
        ),
    ]
