# Generated by Django 6.0.5 on 2026-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporteerror_captura_pantalla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteerror',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Pendiente de revisión', 'Pendiente de revisión'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='Borrador', max_length=30),
        ),
    ]
