# Generated by Django 6.0.5 on 2026-06-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporteerror_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteerror',
            name='captura_pantalla',
            field=models.ImageField(blank=True, null=True, upload_to='reportes_errores/capturas/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='reporteerror',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Pendiente de revisión', 'Pendiente de revisión'), ('en_revision', 'En Revisión'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='Borrador', max_length=30),
        ),
    ]
