# Generated by Django 6.0.5 on 2026-05-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Mercancía')),
                ('ga_porcentaje', models.IntegerField(blank=True, null=True, verbose_name='GA %')),
                ('ice_iehd', models.CharField(blank=True, max_length=50, null=True, verbose_name='ICE - IEHD')),
                ('unidad_medida', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidad de Medida')),
                ('despacho_frontera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Despacho en Frontera')),
                ('doc_tipo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Doc')),
                ('doc_entidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad que emite')),
                ('doc_disposicion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Disp. Legal')),
                ('pref_can_ace', models.CharField(blank=True, max_length=20, null=True, verbose_name='CAN/ACE36/ACE47/VEN')),
                ('pref_ace22_chi', models.CharField(blank=True, max_length=20, null=True, verbose_name='ACE 22 Chi')),
                ('pref_ace22_prot', models.CharField(blank=True, max_length=20, null=True, verbose_name='ACE 22 Prot')),
                ('pref_ace66_mexico', models.CharField(blank=True, max_length=20, null=True, verbose_name='ACE 66 México')),
            ],
            options={
                'verbose_name': 'Arancel',
                'verbose_name_plural': 'Aranceles',
            },
        ),
    ]
